language: ruby
cache: bundler

rvm:
  - jruby
  - 2.0.0
  - 2.1.5
  - 2.2.0

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - brian@murphydye.com
    on_failure: change
    on_success: change
